name: docs
on:
  push:
    branches: [main]
  pull_request:
    paths:
      - 'docs/**'

permissions:
    contents: write
jobs:
  docs-build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # https://github.com/actions/setup-python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # https://github.com/snok/install-poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: |
          poetry install --with docs

      - name: Sphinx build
        run: |
          make docs

  docs-push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # https://github.com/actions/setup-python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # https://github.com/snok/install-poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: |
          poetry install --with docs

      - name: Sphinx build
        run: |
          make doc

      # https://github.com/peaceiris/actions-gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/docs-website' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/
          force_orphan: true
